kind: Invoke
apiVersion: api.ibm.com/v1
metadata:
  name: wM_Invoke
  namespace: wM_Product_Petstore
  version: '1.0'
  tags: []
  labels:
    gatewayTypes:
      - webMethods
spec:
  endpoint:
    http:
      target:
        timeout: 30
        url: https://petstore3.swagger.io/api/v3/
      verb: CUSTOM
  extensions:
    webm-gateway:
      apiVersion: api.ibm.com/v1
